package semconv

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// GenerateFiles writes attribute_keys.go and placement.go into outDir
// (typically internal/semconv/). Both files are formatted with go/format
// so they pass gofmt out of the box.
func GenerateFiles(c *Catalog, outDir string) error {
	if err := writeAttributeKeys(c, filepath.Join(outDir, "attribute_keys.go")); err != nil {
		return err
	}
	if err := writePlacement(c, filepath.Join(outDir, "placement.go")); err != nil {
		return err
	}
	if err := os.WriteFile(
		filepath.Join(outDir, "VERSION"),
		[]byte(c.Version+"\n"),
		0o644,
	); err != nil {
		return fmt.Errorf("write VERSION: %w", err)
	}
	return nil
}

const codegenHeader = `// Code generated by ` + "`vern semconv sync`" + `. DO NOT EDIT.
//
// Regenerate by running: vern semconv sync --apply
// Catalog version: %s

package semconv

`

func writeAttributeKeys(c *Catalog, path string) error {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, codegenHeader, c.Version)
	buf.WriteString("// AttributeKeys is the sorted set of concrete semconv attribute IDs.\n")
	buf.WriteString("// Used by MET-006 to detect metric names that collide with attribute keys.\n")
	buf.WriteString("var AttributeKeys = []string{\n")
	for _, k := range c.AttributeKeys {
		fmt.Fprintf(&buf, "\t%q,\n", k)
	}
	buf.WriteString("}\n")
	return formatAndWrite(buf.Bytes(), path)
}

func writePlacement(c *Catalog, path string) error {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, codegenHeader, c.Version)
	buf.WriteString("// ResourceOnlyKeys contains attribute IDs whose semconv placement is\n")
	buf.WriteString("// resource-only (entity-level). Used by RES-004 to flag misplacement.\n")
	writeKeyList(&buf, "ResourceOnlyKeys", c.LevelKeys(LevelResource))

	buf.WriteString("// SpanOnlyKeys contains attribute IDs whose semconv placement is span-only\n")
	buf.WriteString("// (span or event groups, never resource/log/metric).\n")
	writeKeyList(&buf, "SpanOnlyKeys", c.LevelKeys(LevelSpan))

	buf.WriteString("// LogOnlyKeys contains attribute IDs whose semconv placement is log-only.\n")
	writeKeyList(&buf, "LogOnlyKeys", c.LevelKeys(LevelLog))

	buf.WriteString("// MetricOnlyKeys contains attribute IDs whose semconv placement is metric-only.\n")
	writeKeyList(&buf, "MetricOnlyKeys", c.LevelKeys(LevelMetric))

	return formatAndWrite(buf.Bytes(), path)
}

func writeKeyList(buf *bytes.Buffer, name string, keys []string) {
	fmt.Fprintf(buf, "var %s = []string{\n", name)
	for _, k := range keys {
		fmt.Fprintf(buf, "\t%q,\n", k)
	}
	buf.WriteString("}\n\n")
}

func formatAndWrite(src []byte, path string) error {
	formatted, err := format.Source(src)
	if err != nil {
		return fmt.Errorf("format %s: %w", path, err)
	}
	return os.WriteFile(path, formatted, 0o644)
}

// QuotedCSV renders a slice of keys as a comma-separated quoted list,
// suitable for splicing into ES|QL `IN (...)` expressions.
func QuotedCSV(keys []string) string {
	if len(keys) == 0 {
		return ""
	}
	sorted := append([]string{}, keys...)
	sort.Strings(sorted)
	parts := make([]string, 0, len(sorted))
	for _, k := range sorted {
		parts = append(parts, fmt.Sprintf("%q", k))
	}
	return strings.Join(parts, ", ")
}

// ReadVersionFile returns the contents of <dir>/VERSION (trimmed) or empty.
func ReadVersionFile(dir string) string {
	b, err := os.ReadFile(filepath.Join(dir, "VERSION"))
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(b))
}
